export type SeedSupplierProduct = { name: string; unitRaw: string; pricePerUnit: number };

export const PEDIDOS_SUPPLIERS_FROM_INVENTORY: Record<string, SeedSupplierProduct[]> = {
  'SERHS, S.L.': [
    { name: 'SALSA MOSTAZA MILLAS SOBRE C/300ud', unitRaw: 'CAJA', pricePerUnit: 7.3 },
    { name: 'SALSA CESAR YBARRA 1L C/8', unitRaw: 'UNIDAD', pricePerUnit: 5.14 },
    { name: 'MAIONESA MILLAS 10gr C/230', unitRaw: 'CAJA', pricePerUnit: 10.15 },
    { name: 'LLET COND. ANTIGOTEO 450gr. C/12', unitRaw: 'UNIDAD', pricePerUnit: 2.13 },
    { name: 'KETCHUP 840ml C/12 (BIBERON)', unitRaw: 'UNIDAD', pricePerUnit: 2.12 },
    { name: 'MAIONESA CEDI 1,85Kg C/4', unitRaw: 'UNIDAD', pricePerUnit: 5.69 },
    { name: 'OLI OLIVA CASTER 10ml C/240', unitRaw: 'CAJA', pricePerUnit: 19.0 },
    { name: 'MAIONESA CEDI GALLEDA 5L.', unitRaw: 'UNIDAD', pricePerUnit: 13.83 },
    { name: 'KETCHUP MILLAS 10gr C/275', unitRaw: 'CAJA', pricePerUnit: 8.72 },
    { name: 'OLI SUPERFRID MILLAS B.22KG', unitRaw: 'UNIDAD', pricePerUnit: 53.9 },
    { name: 'OLI GIRASOL HT 5L C/3', unitRaw: 'UNIDAD', pricePerUnit: 8.37 },
    { name: 'MAIONESA 770ml C/12 (BIBERON)', unitRaw: 'UNIDAD', pricePerUnit: 2.85 },
    { name: 'MOSTASSA 800ml C/12 (BIBERON)', unitRaw: 'UNIDAD', pricePerUnit: 2.43 },
    { name: 'VINAGRE CASTER 10ml C/240', unitRaw: 'CAJA', pricePerUnit: 4.84 },
    { name: 'LECHE PRESIDENT DESNATADA 1,5L C/6', unitRaw: 'CAJA', pricePerUnit: 9.38 },
    { name: 'SALSA PESTO GENOVES 930gr', unitRaw: 'UNIDAD', pricePerUnit: 9.0 },
    { name: 'ANIS DEL MONO DOLC 70cl C/6', unitRaw: 'UNIDAD', pricePerUnit: 6.64 },
    { name: 'WHISKY J&B 70cl C/12', unitRaw: 'UNIDAD', pricePerUnit: 9.56 },
    { name: 'RATAFIA RUSSET 70cl', unitRaw: 'UNIDAD', pricePerUnit: 9.66 },
    { name: 'RON PUJOL DAURAT 1L. C/6', unitRaw: 'UNIDAD', pricePerUnit: 12.48 },
    { name: 'BAILEYS 70cl C/6', unitRaw: 'UNIDAD', pricePerUnit: 9.69 },
    { name: 'TRINA TAR. SLEEK 33cl C/24', unitRaw: 'CAJA', pricePerUnit: 12.28 },
    { name: 'VICHY CATALAN SLEEK 33cl C/24', unitRaw: 'CAJA', pricePerUnit: 17.54 },
    { name: 'PICATOSTE TORRATS 500g C/12', unitRaw: 'UNIDAD', pricePerUnit: 2.31 },
  ],
  ANMA: [
    { name: 'SALSA PAPAS BRAVA MILLAS 1.850 GR', unitRaw: 'UNIDAD', pricePerUnit: 5.44 },
    { name: 'SALSA PAPAS BRAVA MILLAS 770ml C/12 (BIBERON)', unitRaw: 'BIBERON 770ml', pricePerUnit: 2.14 },
    { name: 'MANTEQUILLA PASTILLA 15gr RENY PICOT', unitRaw: 'CAJA 100ud', pricePerUnit: 16.01 },
    { name: 'SALSA BARBACOA MILLAS 30gr C/64', unitRaw: 'CAJA 64 UD.', pricePerUnit: 8.51 },
    { name: 'SALSA ALIOLI MILLAS 25ml C/64', unitRaw: 'CAJA 64 UD.', pricePerUnit: 9.74 },
    { name: 'SALSA ALIOLI MILLAS 770ml C/12 (BIBERON)', unitRaw: 'UNIDAD', pricePerUnit: 3.5 },
    { name: 'LECHE SIN LACTOSA ATO 1L C/6', unitRaw: 'CAJA 6ud', pricePerUnit: 8.06 },
    { name: 'SALSA ROSA MILLAS 1,850Kg', unitRaw: 'UNIDAD', pricePerUnit: 4.87 },
    { name: 'COCTEL DE FRUTAS 3Kg C/6', unitRaw: 'UNIDAD', pricePerUnit: 5.71 },
    { name: 'OLIVAS RELLENAS LA SOTA 2Kg', unitRaw: 'UNIDAD', pricePerUnit: 5.15 },
    { name: 'PEPINILLOS 60/80 LA HUERTA 30GR', unitRaw: 'UNIDAD', pricePerUnit: 4.75 },
    { name: 'CINZANO BLANCO LITRO C/6', unitRaw: 'UNIDAD', pricePerUnit: 6.35 },
    { name: 'MYSTIC ESSENCE GIN C/6', unitRaw: 'UNIDAD', pricePerUnit: 6.84 },
    { name: 'TRIPLE SECO 25o CAIMAN 3L. C/4', unitRaw: 'UNIDAD', pricePerUnit: 15.81 },
    { name: 'LICOR MELOCOTON EL TREN 1L. C/12', unitRaw: 'UNIDAD', pricePerUnit: 4.28 },
    { name: 'NEGRITA RON ANEJO 1L. C/6', unitRaw: 'UNIDAD', pricePerUnit: 10.86 },
    { name: 'BRUT MONISTROL 75cl C/6', unitRaw: 'UNIDAD', pricePerUnit: 2.76 },
    { name: 'RIOJA RAMON BILBAO CRIANZA C/12', unitRaw: 'UNIDAD', pricePerUnit: 5.95 },
    { name: 'BLANCO VERDEJO RAMON BILBAO C/6', unitRaw: 'UNIDAD', pricePerUnit: 4.6 },
    { name: 'ORUJO HIERBAS XARIS 70cl C/12', unitRaw: 'UNIDAD', pricePerUnit: 5.19 },
    { name: 'LIMONCELLO LIBERTY 70cl C/6', unitRaw: 'UNIDAD', pricePerUnit: 5.82 },
    { name: 'CREMA ORUJO XARIS 70cl C/12', unitRaw: 'UNIDAD', pricePerUnit: 5.17 },
    { name: 'VERMOUT ROJO MIRO BOX 5L. C/4', unitRaw: 'UNIDAD', pricePerUnit: 14.81 },
    { name: 'LADRON DE MANZANA C/24', unitRaw: 'CAJA', pricePerUnit: 21.5 },
    { name: 'SEVEN UP LATA C/24', unitRaw: 'CAJA', pricePerUnit: 11.04 },
    { name: 'BITTER KAS C/24', unitRaw: 'CAJA', pricePerUnit: 16.09 },
    { name: 'GRANINI MELOCOTON C/12', unitRaw: 'CAJA', pricePerUnit: 11.16 },
    { name: 'GRANINI PINA C/12', unitRaw: 'CAJA', pricePerUnit: 11.16 },
    { name: 'GRANINI NARANJA C/12', unitRaw: 'CAJA', pricePerUnit: 11.16 },
    { name: 'TONICA SCHWEPPES LATA C/24', unitRaw: 'CAJA', pricePerUnit: 13.09 },
    { name: 'CAJA PATATAS A.TORRES 50gr C/25', unitRaw: 'CAJA', pricePerUnit: 16.5 },
    { name: 'CACAO AMARGO POLVO 1Kg C/10', unitRaw: 'UNIDAD', pricePerUnit: 10.66 },
    { name: 'MIEL FLORES 1KG C/6', unitRaw: 'UNIDAD', pricePerUnit: 5.05 },
    { name: 'MERMELADA MELOCOTON HELIOS C/8', unitRaw: 'CAJA', pricePerUnit: 6.8 },
    { name: 'AZUCAR BLANCA SACO 25Kg', unitRaw: 'SACO', pricePerUnit: 17.65 },
    { name: 'AZUCAR GLACE BOLSA 1Kg', unitRaw: 'UNIDAD', pricePerUnit: 2.93 },
    { name: 'MAICENA 2,500Kg', unitRaw: 'UNIDAD', pricePerUnit: 13.25 },
    { name: 'COBERTURA EXTRA BLANCA TRAPA 5KG', unitRaw: 'UNIDAD', pricePerUnit: 63.78 },
    { name: 'COBERTURA EXTRA NEGRA 70% TRAPA 5KG', unitRaw: 'UNIDAD', pricePerUnit: 81.63 },
  ],
  'ALIMENTER, S.A.': [
    { name: 'SALSA BARBACOA C/4 POUCHES BANGOR', unitRaw: 'CAJA', pricePerUnit: 18.61 },
    { name: 'CHEESE DIP C/4 POUCHES BANGOR', unitRaw: 'CAJA', pricePerUnit: 45.22 },
  ],
  'DDI PROVEA S.L.': [
    { name: 'LECHE AVENA LEVATINA 1L C/6', unitRaw: 'CAJA', pricePerUnit: 8.48 },
    { name: 'LECHE ENTERA LETONA 1,5L C/6', unitRaw: 'CAJA', pricePerUnit: 9.58 },
    { name: 'LECHE SOJA LEVATINA 1L. C/6', unitRaw: 'CAJA', pricePerUnit: 8.99 },
    { name: 'DAMM LEMON BARRIL 30', unitRaw: 'BARRIL', pricePerUnit: 63.09 },
    { name: 'TURIA BARRIL 30L.', unitRaw: 'BARRIL', pricePerUnit: 62.2 },
    { name: 'VOLL DAMM 1/3 LATA', unitRaw: 'CAJA', pricePerUnit: 17.36 },
    { name: 'ESTRELLA DAMM 1/3 LATA', unitRaw: 'CAJA', pricePerUnit: 14.65 },
    { name: 'DAURA DAMM 1/3 C/24', unitRaw: 'CAJA', pricePerUnit: 24.49 },
    { name: 'AK DAMM 1/3', unitRaw: 'CAJA', pricePerUnit: 27.39 },
    { name: 'SUERO SANGRIA BARRIL 30L.', unitRaw: 'BARRIL', pricePerUnit: 58.8 },
    { name: 'AGUA VERI 1/2 C/24', unitRaw: 'CAJA', pricePerUnit: 5.33 },
    { name: 'CACAOLAT ORIGINAL C/24', unitRaw: 'CAJA', pricePerUnit: 27.38 },
    { name: 'FREE DAMM 1/3 LATA', unitRaw: 'CAJA', pricePerUnit: 12.88 },
    { name: 'FREE DAMM TOSTADA 1/3 LATA', unitRaw: 'CAJA', pricePerUnit: 12.88 },
  ],
  'CAFES AGUERA': [
    { name: 'ACEITE DE OLIVA V.E', unitRaw: 'UNIDAD', pricePerUnit: 34.9 },
    { name: 'AZUCAR BLANCA BOLSITAS', unitRaw: 'CAJA', pricePerUnit: 18.9 },
    { name: 'AZUCAR MORENO 500ud', unitRaw: 'CAJA', pricePerUnit: 13.55 },
    { name: 'CAFE DESC. GRANO', unitRaw: 'UNIDAD', pricePerUnit: 23.9 },
    { name: 'CAFE ESPECIAL', unitRaw: 'UNIDAD', pricePerUnit: 22.9 },
    { name: 'CAFE DESC. SOBRE C/100', unitRaw: 'CAJA 100ud', pricePerUnit: 10.8 },
    { name: 'EDULCORANTE', unitRaw: 'CAJA', pricePerUnit: 2.9 },
    { name: 'INFUSIONES', unitRaw: 'UNIDAD', pricePerUnit: 9.5 },
    { name: 'VASOS CAFES C/100', unitRaw: 'CAJA', pricePerUnit: 5.0 },
    { name: 'TAPAS CAFES', unitRaw: 'CAJA', pricePerUnit: 2.0 },
    { name: 'PORTAVASOS CAFES', unitRaw: 'UNIDAD', pricePerUnit: 0.15 },
    { name: 'COLACAO SOBRE', unitRaw: 'CAJA', pricePerUnit: 19.9 },
    { name: 'CHOCOLATE TAZA SOBRE C/40', unitRaw: 'CAJA 40ud', pricePerUnit: 12.9 },
  ],
  CARBOMAS: [{ name: 'CARBOMAS SEMI SECO C/12', unitRaw: 'UNIDAD', pricePerUnit: 1.54 }],
  'DAMM BARRIL': [{ name: 'TANQUES ESTRELLA DAMM', unitRaw: 'TANQUE', pricePerUnit: 1497.44 }],
  DISTERRI: [
    { name: 'NESTEA LIMON 1/3 LATA C/24', unitRaw: 'CAJA', pricePerUnit: 10.57 },
    { name: 'NESTEA MARACUYA 1/3 LATA C/24', unitRaw: 'CAJA', pricePerUnit: 10.57 },
  ],
  COCACOLA: [
    { name: 'FANTA LIMON 2L. C/6', unitRaw: 'CAJA', pricePerUnit: 7.69 },
    { name: 'COCACOLA LATA C/24', unitRaw: 'CAJA', pricePerUnit: 14.41 },
    { name: 'COCACOLA ZERO LATA C/24', unitRaw: 'CAJA', pricePerUnit: 13.22 },
    { name: 'FANTA NARANJA LATA C/24', unitRaw: 'CAJA', pricePerUnit: 13.15 },
    { name: 'SPRITE LATA C/24', unitRaw: 'CAJA', pricePerUnit: 13.14 },
    { name: 'AQUARIUS LATA C/24', unitRaw: 'CAJA', pricePerUnit: 14.44 },
    { name: 'COCACOLA ZERO ZERO C/24', unitRaw: 'CAJA', pricePerUnit: 13.22 },
    { name: 'FANTA LIMON C/24', unitRaw: 'CAJA', pricePerUnit: 13.15 },
    { name: 'AQUARIUS NARANJA C/24', unitRaw: 'CAJA', pricePerUnit: 14.44 },
    { name: 'FANTA NARANJA 2L. C/6', unitRaw: 'CAJA', pricePerUnit: 7.69 },
  ],
};
